CXX := g++
LDFLAGS += -ldl

ifneq ($(CLANGDIR),'')
	CLANGPATH=$(CLANGDIR)
else
	#CLANGPATH=$(HOME)/local/clang390debug
	CLANGPATH=$(HOME)/local/clang390release
endif

#CXX := $(CLANGPATH)/bin/clang++

LDFLAGS += -L$(CLANGPATH)/lib
LDFLAGS += -Wl,-rpath,$(CLANGPATH)/lib
LDFLAGS += -Wl,-rpath-link,$(CLANGPATH)/lib

export LD_LIBRARY_PATH := $(CLANGPATH)/lib

LLVM_BIN_PATH := $(CLANGPATH)/bin/

