# compilation options are actually specified in compile_commands.json.  This makefile is just a dummy to invoke the tool.

withstdio.o : withstdio.cpp
	/home/peeterj/toolchain492.clang.debug/bin/tooling_sample withstdio.cpp
