#!/usr/bin/perl

my %flags = (
   'lzmutexx.cpp' => ' -std=c++11',
) ;

print "[\n" ;

my $pwd = `pwd` ; chomp $pwd ;

my $comma = '' ;
foreach my $f (glob( "*.cpp"))
{
   my $flags = " -I$pwd/inc" ;
   $flags .= $flags{$f} if ( defined $flags{$f} ) ;

print qq(${comma}{
  "directory": "$pwd",
  "command": "clang${flags} $f",
  "file": "$f"
}
) ;

   $comma = ',' ; 
}

print "]\n" ;
